### ISSUE TITLE
如果传入数字0，set方法会过滤

### ISSUE THREAD

**Issue by yanyang1116** [jsonchou/zax-url#6]
```
const _url = zaxUrl.set(location.href, {
            test: '0',
            test2: 0
})

// output: http://dev..com/xx/xx/?test=0#/
```
预期，希望0能加上

**Comment by jsonchou** [comment]
@yanyang1116 

已修复

@see [line 186](https://github.com/jsonchou/zax-url/blob/master/__tests__/index.spec.ts#L186)

**Comment by yanyang1116** [comment]
> @yanyang1116
> 
> 已修复
> 
> @see [line 186](https://github.com/jsonchou/zax-url/blob/master/__tests__/index.spec.ts#L186)

牛逼
