### ISSUE TITLE
search 方法的 return 值，预期是 string

### ISSUE THREAD

**Issue by yanyang1116** [jsonchou/zax-url#7]
现状:
```
export declare function search(url: string): IKV;

export declare type IKV = Record<string, string | number>;
```

预期:
在 url 的场景中，应该仅为 string 类型

**Comment by jsonchou** [comment]
@yanyang1116 

已修复

@see [line 186](https://github.com/jsonchou/zax-url/blob/master/__tests__/index.spec.ts#L186)
